#!/usr/bin/env python

import re, subprocess, os
from googletrans import Translator
from google_trans_new import google_translator

# translator = Translator(service_urls=['translate.googleapis.com'])
translatorNew = google_translator(url_suffix='us')

def clearResponse(response):
    return str(re.findall(r"b\'([\w\W]+)\\n", str(response))[0])

languages = {'Detect Language' : 'auto' , 'Afrikaans': 'af', 'Albanian': 'sq', 'Amharic': 'am', 'Arabic': 'ar', 'Armenian': 'hy',
             'Azerbaijani': 'az', 'Basque': 'eu', 'Belarusian': 'be', 'Bengali': 'bn', 'Bosnian': "bs",
             "Bulgarian": 'bg', "Catalan": "ca", "Cebuano": 'ceb', 'Chinese (Simplified)': 'zh-CN',
             'Chinese (Traditional)': 'zh-TW', 'Corsican': 'co', 'Croatian': 'hr', 'Czech': 'cs', 'Danish': 'da' ,
             "Dutch": 'nl', 'English': 'en', 'Esperanto': 'eo', 'Estonian': 'et', 'Finnish': 'fi', 'French': 'fr',
             'Frisian': 'fy', 'Galician': 'gl' , 'Georgian' : 'ka' , 'German' : 'de' , 'Greek': 'el' , 'Gujarati': 'gu' ,
             'Haitian Creole' : 'ht' , 'Hausa' : 'ha' , 'Hawaiian': 'haw', 'Hebrew': 'he', 'Hindi': 'hi', 'Hmong': 'hmn' ,
             'Hungarian' : 'hu', 'Icelandic' : 'is', 'Igbo' : 'ig', 'Indonesian' : 'id', 'Irish': 'ga', 'Italian': 'it',
             'Japanese': 'ja', 'Javanese': 'jv', 'Kannada': 'kn', 'Kazakh': 'kk', 'Khmer': 'km', 'Kinyarwanda': 'rw',
             'Korean': 'ko', 'Kurdish': 'ku', 'Kyrgyz': 'ky', 'Lao': 'lo', 'Latin': 'la', 'Latvian': 'lv',
             'Lithuanian': 'lt', 'Luxembourgish': 'lb', 'Macedonian': 'mk', 'Malagasy': 'mg', 'Malay': 'ms',
             'Malayalam': 'ml', 'Maltese': 'mt', 'Maori': 'mi', 'Marathi': 'mr', 'Mongolian': 'mn',
             'Myanmar (Burmese)': 'my', 'Nepali': 'ne', 'Norwegian': 'no', 'Nyanja (Chichewa)': 'ny',
             'Odia (Oriya) or Pashto' : 'ps', 'Persian': 'fa', 'Polish': 'pl', 'Portuguese (Portugal, Brazil)' : 'pt',
             'Punjabi': 'pa', 'Romanian': 'ro', 'Russian': 'ru', 'Samoan': 'sm', 'Scots Gaelic' : 'gd', 'Serbian' : 'sr' ,
             'Sesotho' : 'st' , 'Shona' : 'sn' , 'Sindhi' : 'sd' , 'Sinhala (Sinhalese)' : 'si', 'Slovak': 'sk',
             'Slovenian': 'sl', 'Somali': 'so', 'Spanish': 'es', 'Sundanese': 'su', 'Swahili': 'sw', 'Swedish': 'sv',
             'Tagalog (Filipino)' : 'tl' , 'Tajik': 'tg', 'Tamil': 'ta', 'Tatar': 'tt', 'Telugu': 'te', 'Thai':  'th',
             'Turkish': 'tr', 'Turkmen': 'tk', 'Ukrainian': 'uk', 'Urdu': 'ur', 'Uyghur': 'ug', 'Uzbek': 'uz',
             'Vietnamese': 'vi', 'Welsh': 'cy', 'Xhosa': 'xh', 'Yiddish': 'yi', 'Yoruba': 'yo', 'Zulu': 'zu'}

def getLanguage():
    toLang = languages.copy()
    del toLang['Detect Language']
    languagesJoined = '\n'.join(toLang.keys())
    languageRaw = subprocess.check_output(f"echo -e '{languagesJoined}' | dmenu -p 'Translate to:' | xargs -I % echo '%'", shell=True)
    return languages[clearResponse(languageRaw)]

def getFromLanguage():
    languagesJoined = '\n'.join(languages.keys())
    languageRaw = subprocess.check_output(f"echo -e '{languagesJoined}' | dmenu -p 'Translate from:' | xargs -I % echo '%'", shell=True)
    return languages[clearResponse(languageRaw)]

def getWord():
    wordRaw = subprocess.check_output("echo -e | dmenu -p 'Word to translate' | xargs -I % echo '%'", shell=True)
    return clearResponse(wordRaw)

def translate():
    # text = translator.translate(text=getWord(), src=getFromLanguage(),  dest=getLanguage()).text
    text = translatorNew.translate(getWord(), lang_src=getFromLanguage(), lang_tgt=getLanguage())
    answer = subprocess.check_output(f"echo -e 'Copy to clipboard\nAnother Word\nClose'| dmenu -p '{text}'", shell=True)
    if 'Copy' in str(answer):
        os.system(f"echo -n '{text}' | xclip -selection clipboard")
    elif 'Another' in str(answer):
        translate()
    else:
        pass

translate()


